development:
  adapter: postgresql
  database: social_network_development

test:
  adapter: postgresql
  database: social_network_test

production:
  adapter: postgresql
  database: social_network_production
